### ISSUE TITLE
Could not compile on Rust 1.10 nightly

### ISSUE THREAD

**Issue by Ronaldho80** [novocaine/rust-python-ext#3]
Ubuntu 16.04/GNOME 

```
$ rustc --version
rustc 1.10.0-nightly (6974800c6 2016-05-08)

$ cargo build
   Compiling utf8-ranges v0.1.3
   Compiling interpolate_idents v0.0.3
error: unresolved import `rustc::plugin::Registry`. Could not find `plugin` in `rustc` [--explain E0432]
 --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/lib.rs:6:5
6 |> use rustc::plugin::Registry;
  |>     ^^^^^^^^^^^^^^^^^^^^^^^

error: unresolved import `syntax::ast::TokenTree::TtToken`. There is no `TtToken` in `syntax::ast::TokenTree`. Did you mean to use `Token`? [--explain E0432]
 --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/lib.rs:8:36
8 |> use syntax::ast::TokenTree::{self, TtToken};
  |>                                    ^^^^^^^

error: unresolved import `syntax::parse::token::IdentStyle`. There is no `IdentStyle` in `syntax::parse::token` [--explain E0432]
  --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/lib.rs:11:53
11 |> use syntax::parse::token::{self, DelimToken, Token, IdentStyle};
   |>                                                     ^^^^^^^^^^

error: unresolved import `syntax::diagnostic::FatalError`. Could not find `diagnostic` in `syntax` [--explain E0432]
  --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs:14:13
14 |>         use syntax::diagnostic::FatalError;
   |>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs:14:13: 14:43: note: in this expansion of panictry! (defined in /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs)

error: unresolved import `syntax::diagnostic::FatalError`. Could not find `diagnostic` in `syntax` [--explain E0432]
  --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs:14:13
14 |>         use syntax::diagnostic::FatalError;
   |>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs:14:13: 14:43: note: in this expansion of panictry! (defined in /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs)

error: `TtToken` is not an enum variant, struct or const [E0418]
  --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/lib.rs:31:26
31 |>                         &TtToken(ref span, Token::Ident(ref ident, IdentStyle::Plain)) => {
   |>                          ^^^^^^^

error: method `make_impl_items` has an incompatible type for trait:
 expected struct `syntax::ast::ImplItem`,
    found struct `syntax::ptr::P` [--explain E0053]
  --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs:74:5
74 |>     fn make_impl_items(self: Box<ParserAnyMacro<'a>>)
   |>     ^

error: method `make_stmts` has an incompatible type for trait:
 expected struct `syntax::codemap::Spanned`,
    found struct `syntax::ptr::P` [--explain E0053]
  --> /home/herzog/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.0.3/src/parser_any_macro.rs:88:5
88 |>     fn make_stmts(self: Box<ParserAnyMacro<'a>>)
   |>     ^

error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
error: Could not compile `interpolate_idents`.

To learn more, run the command again with --verbose.
```

**Comment by novocaine** [comment]
This is a problem with rust-cpython, not this setup helper.
